/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoravoz;

import Voz.ReconocimientoVoz;
import javax.swing.JOptionPane;

public class CalculadoraCientifica extends javax.swing.JFrame implements Runnable {

    private double operando1;
    private double operando2;
    private double resultado=0.0;
    
    /**Permite saber si se ejecuto una accion matematica*/
    private boolean presionadoAccion;
    
    /**Permite saber cuan es la accion(Operacion) matematica que se ejecuto*/
    private int accion;
    public ReconocimientoVoz escuchar;
    public Thread hiloEscucha;

    public CalculadoraCientifica() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setVisible(true);
        this.presionadoAccion = false;
        this.txtNumero.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        txtNumero = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        btnRaiz = new javax.swing.JButton();
        btnInversa = new javax.swing.JButton();
        btnAbsoluto = new javax.swing.JButton();
        btnModulo = new javax.swing.JButton();
        btnBorrarTodo = new javax.swing.JButton();
        btnX_Y = new javax.swing.JButton();
        btnBase_2 = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnX_3 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnMultiplicacion = new javax.swing.JButton();
        btnX_2 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnBorrarTodo1 = new javax.swing.JButton();
        Mas_Menos = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnComa = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jButton9.setText("jButton9");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 229, 255));
        setResizable(false);

        txtNumero.setEditable(false);
        txtNumero.setBackground(new java.awt.Color(255, 255, 255));
        txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumero.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(6, 0));

        btnRaiz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRaiz.setText("sqrt(x)");
        btnRaiz.setContentAreaFilled(false);
        btnRaiz.setPreferredSize(new java.awt.Dimension(45, 37));
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });
        jPanel1.add(btnRaiz);

        btnInversa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInversa.setText("1/x");
        btnInversa.setContentAreaFilled(false);
        btnInversa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInversaActionPerformed(evt);
            }
        });
        jPanel1.add(btnInversa);

        btnAbsoluto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAbsoluto.setText("| x |");
        btnAbsoluto.setContentAreaFilled(false);
        btnAbsoluto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsolutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAbsoluto);

        btnModulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModulo.setText("mod");
        btnModulo.setContentAreaFilled(false);
        btnModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloActionPerformed(evt);
            }
        });
        jPanel1.add(btnModulo);

        btnBorrarTodo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBorrarTodo.setText("C");
        btnBorrarTodo.setContentAreaFilled(false);
        btnBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarTodo);

        btnX_Y.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnX_Y.setText("X^Y");
        btnX_Y.setContentAreaFilled(false);
        btnX_Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX_YActionPerformed(evt);
            }
        });
        jPanel1.add(btnX_Y);

        btnBase_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBase_2.setText("2^X");
        btnBase_2.setContentAreaFilled(false);
        btnBase_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBase_2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBase_2);

        btnPi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadoravoz/pi.png"))); // NOI18N
        btnPi.setContentAreaFilled(false);
        btnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiActionPerformed(evt);
            }
        });
        jPanel1.add(btnPi);

        btnFactorial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFactorial.setText("n!");
        btnFactorial.setContentAreaFilled(false);
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });
        jPanel1.add(btnFactorial);

        btnDivision.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDivision.setText("/");
        btnDivision.setContentAreaFilled(false);
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivision);

        btnX_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnX_3.setText("X^3");
        btnX_3.setContentAreaFilled(false);
        btnX_3.setMaximumSize(new java.awt.Dimension(75, 50));
        btnX_3.setMinimumSize(new java.awt.Dimension(75, 50));
        btnX_3.setPreferredSize(new java.awt.Dimension(75, 50));
        btnX_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX_3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnX_3);

        btn7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn7.setText("7");
        btn7.setContentAreaFilled(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7);

        btn8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn8.setText("8");
        btn8.setContentAreaFilled(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8);

        btn9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn9.setText("9");
        btn9.setContentAreaFilled(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9);

        btnMultiplicacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMultiplicacion.setText("X");
        btnMultiplicacion.setContentAreaFilled(false);
        btnMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(btnMultiplicacion);

        btnX_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnX_2.setText("X^2");
        btnX_2.setContentAreaFilled(false);
        btnX_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX_2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnX_2);

        btn4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn4.setText("4");
        btn4.setContentAreaFilled(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4);

        btn5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn5.setText("5");
        btn5.setContentAreaFilled(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5);

        btn6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn6.setText("6");
        btn6.setContentAreaFilled(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6);

        btnResta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnResta.setText("-");
        btnResta.setContentAreaFilled(false);
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });
        jPanel1.add(btnResta);

        btnLog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLog.setText("log");
        btnLog.setContentAreaFilled(false);
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });
        jPanel1.add(btnLog);

        btn1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn1.setText("1");
        btn1.setContentAreaFilled(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1);

        btn2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn2.setText("2");
        btn2.setContentAreaFilled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2);

        btn3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn3.setText("3");
        btn3.setContentAreaFilled(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3);

        btnSuma.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSuma.setText("+");
        btnSuma.setContentAreaFilled(false);
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSuma);

        btnBorrarTodo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBorrarTodo1.setForeground(new java.awt.Color(255, 0, 0));
        btnBorrarTodo1.setText("INIT");
        btnBorrarTodo1.setContentAreaFilled(false);
        btnBorrarTodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarTodo1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarTodo1);

        Mas_Menos.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Mas_Menos.setText("+/-");
        Mas_Menos.setContentAreaFilled(false);
        Mas_Menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mas_MenosActionPerformed(evt);
            }
        });
        jPanel1.add(Mas_Menos);

        btn0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn0.setText("O");
        btn0.setContentAreaFilled(false);
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0);

        btnComa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnComa.setText(",");
        btnComa.setContentAreaFilled(false);
        btnComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComaActionPerformed(evt);
            }
        });
        jPanel1.add(btnComa);

        btnResultado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnResultado.setText("=");
        btnResultado.setContentAreaFilled(false);
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(btnResultado);

        jMenu1.setText("Calculadora");

        jMenuItem1.setText("Estándar");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Científica");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tema");

        jMenuItem4.setText("Claro");
        jMenu2.add(jMenuItem4);

        jMenuItem3.setText("Oscuro");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNumero)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        this.undirBoton((byte) 1);
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        this.undirIgual();
    }//GEN-LAST:event_btnResultadoActionPerformed

    public void undirIgual() {
        this.operando2 = Double.parseDouble(this.txtNumero.getText());
        this.mostrarResultado();
    }

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        this.undirBoton(2);
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        this.undirBoton(4);
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicacionActionPerformed
        this.undirBoton(3);
    }//GEN-LAST:event_btnMultiplicacionActionPerformed

    private void btnBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodoActionPerformed
        this.borrarTodo();
    }//GEN-LAST:event_btnBorrarTodoActionPerformed

    private void btnBorrarTodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarTodo1ActionPerformed
        this.iniciarReconocimieto();
        JOptionPane.showMessageDialog(rootPane, "Reconocimiento de voz iniciado"
                + "\ncorrectamente....!!", "Comando", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnBorrarTodo1ActionPerformed

    private void Mas_MenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mas_MenosActionPerformed
       this.undirBoton(14);
    }//GEN-LAST:event_Mas_MenosActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        this.escribirEnPantalla("0");
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComaActionPerformed
        this.escribirEnPantalla(".");
    }//GEN-LAST:event_btnComaActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        this.undirBoton(7);
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloActionPerformed
        this.undirBoton(5);
    }//GEN-LAST:event_btnModuloActionPerformed

    private void btnX_YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX_YActionPerformed
        this.undirBoton(6);
    }//GEN-LAST:event_btnX_YActionPerformed

    private void btnX_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX_2ActionPerformed
        this.undirBoton(8);
    }//GEN-LAST:event_btnX_2ActionPerformed

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        this.undirBoton(9);
    }//GEN-LAST:event_btnRaizActionPerformed

    private void btnInversaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInversaActionPerformed
        this.undirBoton(10);
    }//GEN-LAST:event_btnInversaActionPerformed

    private void btnAbsolutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsolutoActionPerformed
        this.undirBoton(11);
    }//GEN-LAST:event_btnAbsolutoActionPerformed

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        this.undirBoton(12);
    }//GEN-LAST:event_btnFactorialActionPerformed

    private void btnX_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX_3ActionPerformed
        this.undirBoton(13);
    }//GEN-LAST:event_btnX_3ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        this.escribirEnPantalla("1");
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
       this.escribirEnPantalla("2");
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        this.escribirEnPantalla("3");
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        this.escribirEnPantalla("4");
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        this.escribirEnPantalla("5");
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        this.escribirEnPantalla("6");
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        this.escribirEnPantalla("7");
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        this.escribirEnPantalla("8");
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        this.escribirEnPantalla("9");
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiActionPerformed
        double pi = Math.PI;
        this.escribirEnPantalla(Double.toString(pi));
    }//GEN-LAST:event_btnPiActionPerformed

    private void btnBase_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBase_2ActionPerformed
        this.undirBoton(15);
    }//GEN-LAST:event_btnBase_2ActionPerformed

    public void borrarTodo() {
        this.txtNumero.setText("");
    }

    private void iniciarReconocimieto() {
        hiloEscucha = new Thread(escuchar = new ReconocimientoVoz(this));
        hiloEscucha.start();
    }

    public void undirBoton(int accion) {
        this.operando1 = Double.parseDouble(this.txtNumero.getText());
        this.txtNumero.setText("");
        this.accion = accion;
        if(this.accion >= 7){
            OperacionesCientificas();
        }
    }
    public void OperacionesCientificas(){
        
        switch (this.accion) {
            case 7:
                this.resultado = Math.log10(this.operando1);
                break;
            case 8:
                this.resultado = Math.pow(this.operando1,2);
                break;
            case 9:
                this.resultado = Math.sqrt(this.operando1);
                break;
            case 10:
                this.resultado = 1/(this.operando1);
                break;
            case 11:
                this.resultado = Math.abs(this.operando1);
                break;
            case 12:
                this.resultado = Factorial(this.operando1);
                break;  
            case 13:
                this.resultado = Math.pow(this.operando1,3);
                break;
            case 14:                
                this.resultado = -1*this.operando1;
                break;
            case 15:                
                this.resultado = Math.pow(2,this.operando1);
                break;
            
        }
        this.presionadoAccion = false;
        this.txtNumero.setText(Double.toString(this.resultado));
    }
    
    private static double Factorial(double valor) {
        if(valor == 0 || valor == 1){
            return 1.0;
        }
        else{
            return valor*Factorial(valor-1);
        }
    }
    public void mostrarResultado() {
        switch (this.accion) {
            case 1:
                this.resultado = this.operando1 + this.operando2;
                break;
            case 2:
                this.resultado = this.operando1 - this.operando2;
                break;
            case 3:
                this.resultado = this.operando1 * this.operando2;
                break;
            case 4:
                this.resultado = this.operando1 / this.operando2;
                break;
            case 5:
                this.resultado = this.operando1 % this.operando2;
                break;
            case 6:
                this.resultado = Math.pow(this.operando1 , this.operando2);
                break;
        }
        this.presionadoAccion = false;
        this.txtNumero.setText(Double.toString(this.resultado));
        
    }

    /**
     * Escribe en la pantalla un numero(0 a 9), que es representado como un
     * caracter de tipo string
     *
     * @param numero string que representa un numero del 0 a 9, se debe tener
     * cuidado este parametro es un string y no se puede operar solo se mostrara
     * en la pantalla de la calculadora
     */
    public void escribirEnPantalla(String numero) {
        this.txtNumero.setText(this.txtNumero.getText() + numero);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Mas_Menos;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAbsoluto;
    private javax.swing.JButton btnBase_2;
    public javax.swing.JButton btnBorrarTodo;
    private javax.swing.JButton btnBorrarTodo1;
    private javax.swing.JButton btnComa;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnInversa;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnModulo;
    private javax.swing.JButton btnMultiplicacion;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnResultado;
    private javax.swing.JButton btnSuma;
    private javax.swing.JButton btnX_2;
    private javax.swing.JButton btnX_3;
    private javax.swing.JButton btnX_Y;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JFormattedTextField txtNumero;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
